# Generated by Django 3.2 on 2022-06-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220602_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
